### ISSUE TITLE
Document PubSub changes from go-ipfs v0.11

### ISSUE THREAD

**Issue by TheDiscordian** [ipfs/ipfs-docs#1007] opened 2022-01-26 23:19 UTC
This describes the issue very well: https://github.com/ipfs/go-ipfs/issues/8612

Caused by: https://github.com/ipfs/go-ipfs/issues/8343

Relevant areas: https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-pub && https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-sub (Edit: This actually doesn't effect `sub`, details below!)

Basically, we used to accept regular strings for pubsub topics over the HTTP API, now we require Base64URL encoding **prefixed with a 'u'** (Edit: As outlined below, this isn't *entirely* true, Base64URL is the default/recommended encoding, but technically any multibase should work https://github.com/multiformats/multibase, which is where the `u` comes from). Noting this down in an issue so I don't forget, I spun my wheels on this for a while not realizing this change happened, this is probably a good first issue though.

Also not sure how other APIs have been effected. I believe the CLI handles this for you for example.

**Comment by Annamarie2019** [comment] 2022-03-01 21:37
We made a change and it's causing bugs. We used to accept regular strings for pubsub topics over the HTTP API, now we require Base64URL encoding prefixed with a 'u'.
These docs need to be fixed: https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-pub && https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-sub
Needs analysis as to whether other APIs are affected.

**Comment by TMoMoreau** [comment] 2022-03-07 16:14
Fix for the areas specified by @TheDiscordian at PR #1046

**Comment by Annamarie2019** [comment] 2022-03-08 00:00
@TMoMoreau or @TheDiscordian  Sorry, I'm new to Base64URL encoding and can't find any discussion of it in respect to a prefix. (46 seems to mean `u`, but that doesn't help me any). I don't know how to prefix the `u`. Is there a . or an _ ? Is this doc correct (I bolded what I changed):

### Arguments

- `arg` [string]: Topic to publish to. Required: **yes**. **Requires Base64URL encoding, prefixed with `u`.**

### Request Body

Argument `data` is of file type. This endpoint expects one or several files (depending on the command) in the body of the request as **`umultipart/form-data`**.

As for affecting other APIs, publish is the only one that writes and has a Request Body, so it seemed to me that that's the only one to change. Is that correct thinking? (To read existing stuff, you'd have to call it by whatever it's named.)

**Comment by TheDiscordian** [comment] 2022-03-08 00:15
@Annamarie2019 The `u` comes from multibase encoding: https://github.com/multiformats/multibase. So technically prefixes other than `u` are possible for other bases. I tested out your theory that this only effects `publish` and not `subscribe`, you're totally correct there.

**Comment by Annamarie2019** [comment] 2022-03-08 20:01
@TheDiscordian @TMoMoreau 

For reference, this is what the [article](https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-pub) says now:
_______
### /api/v0/pubsub/pub

Publish data to a given pubsub topic.

Arguments
arg [string]: Topic to publish to. Required: yes.

Request Body
Argument data is of file type. This endpoint expects one or several files (depending on the command) in the body of the request as 'multipart/form-data'.
_______

I'll display my ignorance here, in case it helps the cause, but I don't understand:

- "of file type"... Do we mean, "Argument `data` is the endpoint, which expects one or more files"?
- "depending on the command"....I thought we were defining the command: `pub`.... Does it mean "sub-command" or "argument"? (such as " ipfs multibase encode <file>  - Encode data into multibase string " ...from entering `ipfs multibase u --help` in cli)
- "as" .... meaning "such as" (introducing an example) or "in the format of"
- the original says "as `multipart/form-data` Multibase format is `<base-encoding-character><base-encoded-data>`".....does `multipart/form-data` need some explanation? (See [What does multipart/form-data mean?](https://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean) and [HTML | <form> enctype Attribute](https://www.geeksforgeeks.org/html-form-enctype-attribute/) ) How do you format multiple files?

Other than `u`, are other bases possible? under what conditions?

**Comment by TheDiscordian** [comment] 2022-03-08 20:51
`data` is out of scope of this issue (hasn't been changed). `arg` is what this issue is about, and the formats other than `u` (`Base64URL`) are defined here: https://github.com/multiformats/multibase, as I outlined above.

**Comment by TMoMoreau** [comment] 2022-03-08 22:05
Updated PR to document the changes that this issue specified. #1065

**Comment by lidel** [comment] 2022-03-08 23:19
Related: https://github.com/ipfs/go-ipfs-cmds/issues/224

**Comment by Annamarie2019** [comment] 2022-03-09 00:00
Thanks, @TheDiscordian I read so much stuff, that i forgot where I started: "we used to accept regular strings for pubsub topics...now we require....." (Duh!) So how's this for the update:

Arguments
arg [string]: Topic to publish to. Required: yes. Requires multibase encoding. The default and recommended encoding is `u` for base64url, but you can use any base encoding character. See the Multibase Table at [multibase](https://github.com/multiformats/multibase).

**Comment by Annamarie2019** [comment] 2022-03-09 00:14
@TMoMoreau Thanks. Your explanation in #1065 is great, but if we have it up by the argument, maybe after the curl example, all we need to say is, something like: 

`curl -X POST -F file=@myfile "http://127.0.0.1:5001/api/v0/pubsub/pub?arg=u<topic>"`
Note the `u` prefix before the topic name, satisfying the argument requirement to be base-encoded.

**Comment by Annamarie2019** [comment] 2022-03-14 17:48
@TMoMoreau @TheDiscordian Should we add the u prefix and link to this explanation for https://docs.ipfs.io/reference/cli/#ipfs-pubsub in the subcommands (maybe tick marks around those commands as well).

**Comment by lidel** [comment] 2022-04-05 00:28
iirc  all `ipfs pubsub *` commands got fixed to use multibase  when topic is passed as `arg` (https://github.com/ipfs/go-ipfs/pull/8183#pullrequestreview-788614321) so this impacts  both `pub` and `sub`. 


The proposed  bandaid is fine until https://github.com/ipfs/go-ipfs-cmds/issues/224 is addressed :+1: 

There is a small caveat tho: `ipfs` command line client will do the multibase conversion for you automatically. So on the CLI you use regular strings, and the conversion happens behind the scenes before the wire format is sent over HTTP RPC.

Due to this, we need to clarify that in a way that looks acceptable on both HTTP RPC API reference page, and when user reads `ipfs pubsub pub --help` (unfortunately, the same text is displayed in both places).

Pubsub commands are marked as experimental, so we don't need to stress too much about this, does not have to be pretty.

Maybe `(multibase encoded when sent over HTTP RPC)` ?

**Comment by BigLep** [comment] 2022-05-06 15:50
Closing this since https://github.com/ipfs/go-ipfs/pull/8933 was merged

**Closed by BigLep** 2022-05-06 15:50 UTC
Labels: dif/easy, good first issue, P1, kind/bug, need/maintainers-input, effort/days

**Comment by lidel** [comment] 2022-05-16 13:05
Remaining work documented in https://github.com/ipfs/ipfs-docs/issues/1146
