### ISSUE TITLE
Peering with content providers: Cloudflare info outdated

### ISSUE THREAD

**Issue by tgies** [ipfs/ipfs-docs#1170] opened 2022-06-08 14:26 UTC
As far as I can tell [the info here](https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list) about peering with Cloudflare is outdated. Neither of the addresses posted are listening on port 4009 as indicated (connection immediately resets when I telnet to them), and trying to connect ipfs (built from git master) to them fails like so:

```
$ ipfs swarm connect /ip4/172.65.0.13/tcp/4009/p2p/QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP
Error: connect QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP failure: failed to dial QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP:
  * [/ip4/172.65.0.13/tcp/4009] failed to negotiate security protocol: read tcp4 172.18.0.2:4001->172.65.0.13:4009: read: connection reset by peer
```

I can successfully connect manually to other peers including many of the other listed content providers on that page. It looks to me like Cloudflare just changed their setup.

Perhaps it is no longer possible to directly peer to Cloudflare (just speculating, but I would not be surprised if they changed this _because_ they had some kind of issue with people knowing how to manually dial them) but if it is I would love the updated details. Thanks!

**Comment by ElPaisano** [comment] 2023-08-21 23:57
Looks like the Cloudflare peer IDs were updated in August 2022 https://github.com/ipfs/ipfs-docs/pull/1171. I've also confirmed that the peer IDs are working. This is the output of a sh script that runs `ipfs ping` on all of the Cloudflare peer IDs:

```
Pinging Peer ID: QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE
Looking up peer QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE
PING QmcFf2FH3CEgTNHeMRGhN7HNHU1EXAxoEk6EFuSyXCsvRE.
Pong received: time=74.44 ms
Pong received: time=71.84 ms
Pong received: time=72.36 ms
Pong received: time=71.15 ms
Pong received: time=68.48 ms
Pong received: time=70.83 ms
Pong received: time=77.50 ms
Pong received: time=67.25 ms
Pong received: time=90.74 ms
Pong received: time=72.55 ms
Average latency: 73.71ms
Pinging Peer ID: QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z
Looking up peer QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z
PING QmcFmLd5ySfk2WZuJ1mfSWLDjdmHZq7rSAua4GoeSQfs1z.
Pong received: time=74.86 ms
Pong received: time=80.61 ms
Pong received: time=85.66 ms
Pong received: time=70.67 ms
Pong received: time=70.83 ms
Pong received: time=78.85 ms
Pong received: time=75.00 ms
Pong received: time=77.96 ms
Pong received: time=68.38 ms
Pong received: time=82.96 ms
Average latency: 76.58ms
Pinging Peer ID: QmcfFmzSDVbwexQ9Au2pt5YEXHK5xajwgaU6PpkbLWerMa
Looking up peer QmcfFmzSDVbwexQ9Au2pt5YEXHK5xajwgaU6PpkbLWerMa
PING QmcfFmzSDVbwexQ9Au2pt5YEXHK5xajwgaU6PpkbLWerMa.
Pong received: time=98.86 ms
Pong received: time=88.55 ms
Pong received: time=91.60 ms
Pong received: time=98.91 ms
Pong received: time=89.98 ms
Pong received: time=89.58 ms
Pong received: time=93.41 ms
Pong received: time=87.31 ms
Pong received: time=92.64 ms
Pong received: time=101.67 ms
Average latency: 93.25ms
Pinging Peer ID: QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx
Looking up peer QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx
PING QmcfJeB3Js1FG7T8YaZATEiaHqNKVdQfybYYkbT1knUswx.
Pong received: time=84.37 ms
Pong received: time=83.41 ms
Pong received: time=81.52 ms
Pong received: time=80.31 ms
Pong received: time=98.65 ms
Pong received: time=102.38 ms
Pong received: time=191.46 ms
Pong received: time=81.76 ms
Pong received: time=81.10 ms
Pong received: time=76.70 ms
Average latency: 96.17ms
Pinging Peer ID: QmcfVvzK4tMdFmpJjEKDUoqRgP4W9FnmJoziYX5GXJJ8eZ
Looking up peer QmcfVvzK4tMdFmpJjEKDUoqRgP4W9FnmJoziYX5GXJJ8eZ
PING QmcfVvzK4tMdFmpJjEKDUoqRgP4W9FnmJoziYX5GXJJ8eZ.
Pong received: time=78.57 ms
Pong received: time=83.42 ms
Pong received: time=70.73 ms
Pong received: time=109.31 ms
Pong received: time=80.42 ms
Pong received: time=72.82 ms
Pong received: time=77.00 ms
Pong received: time=117.07 ms
Pong received: time=70.83 ms
Pong received: time=69.28 ms
Average latency: 82.95ms
Pinging Peer ID: QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G
Looking up peer QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G
PING QmcfZD3VKrUxyP9BbyUnZDpbqDnT7cQ4WjPP8TRLXaoE7G.
Pong received: time=158.05 ms
Pong received: time=83.02 ms
Pong received: time=78.34 ms
Pong received: time=78.72 ms
Pong received: time=79.81 ms
Pong received: time=84.05 ms
Pong received: time=75.52 ms
Pong received: time=84.91 ms
Pong received: time=84.90 ms
Pong received: time=80.95 ms
Average latency: 88.83ms
Pinging Peer ID: QmcfZP2LuW4jxviTeG8fi28qjnZScACb8PEgHAc17ZEri3
Looking up peer QmcfZP2LuW4jxviTeG8fi28qjnZScACb8PEgHAc17ZEri3
PING QmcfZP2LuW4jxviTeG8fi28qjnZScACb8PEgHAc17ZEri3.
Pong received: time=97.73 ms
Pong received: time=90.25 ms
Pong received: time=78.33 ms
Pong received: time=82.97 ms
Pong received: time=77.26 ms
Pong received: time=84.15 ms
Pong received: time=95.92 ms
Pong received: time=85.07 ms
Pong received: time=86.21 ms
Pong received: time=97.78 ms
Average latency: 87.57ms
Pinging Peer ID: QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP
Looking up peer QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP
PING QmcfgsJsMtx6qJb74akCw1M24X1zFwgGo11h1cuhwQjtJP.
Pong received: time=88.07 ms
Pong received: time=85.02 ms
Pong received: time=116.63 ms
Pong received: time=91.21 ms
Pong received: time=82.02 ms
Pong received: time=110.19 ms
Pong received: time=122.67 ms
Pong received: time=85.52 ms
Pong received: time=74.69 ms
Pong received: time=88.04 ms
Average latency: 94.41ms
Pinging Peer ID: Qmcfr2FC7pFzJbTSDfYaSy1J8Uuy8ccGLeLyqJCKJvTHMi
Looking up peer Qmcfr2FC7pFzJbTSDfYaSy1J8Uuy8ccGLeLyqJCKJvTHMi
PING Qmcfr2FC7pFzJbTSDfYaSy1J8Uuy8ccGLeLyqJCKJvTHMi.
Pong received: time=106.10 ms
Pong received: time=101.57 ms
Pong received: time=114.70 ms
Pong received: time=86.06 ms
Pong received: time=82.56 ms
Pong received: time=83.87 ms
Pong received: time=77.68 ms
Pong received: time=76.62 ms
Pong received: time=74.18 ms
Pong received: time=82.20 ms
Average latency: 88.55ms
Pinging Peer ID: QmcfR3V5YAtHBzxVACWCzXTt26SyEkxdwhGJ6875A8BuWx
Looking up peer QmcfR3V5YAtHBzxVACWCzXTt26SyEkxdwhGJ6875A8BuWx
PING QmcfR3V5YAtHBzxVACWCzXTt26SyEkxdwhGJ6875A8BuWx.
Pong received: time=94.58 ms
Pong received: time=78.62 ms
Pong received: time=102.06 ms
Pong received: time=108.66 ms
Pong received: time=83.06 ms
Pong received: time=79.77 ms
Pong received: time=89.08 ms
Pong received: time=214.91 ms
Pong received: time=92.31 ms
Pong received: time=97.58 ms
Average latency: 104.06ms
Pinging Peer ID: Qmcfuo1TM9uUiJp6dTbm915Rf1aTqm3a3dnmCdDQLHgvL5
Looking up peer Qmcfuo1TM9uUiJp6dTbm915Rf1aTqm3a3dnmCdDQLHgvL5
PING Qmcfuo1TM9uUiJp6dTbm915Rf1aTqm3a3dnmCdDQLHgvL5.
Pong received: time=63.16 ms
Pong received: time=60.01 ms
Pong received: time=65.27 ms
Pong received: time=54.36 ms
Pong received: time=73.91 ms
Pong received: time=291.35 ms
Pong received: time=61.25 ms
Pong received: time=65.00 ms
Pong received: time=57.86 ms
Pong received: time=59.10 ms
Average latency: 85.13ms
Pinging Peer ID: QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev
Looking up peer QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev
PING QmcfV2sg9zaq7UUHVCGuSvT2M2rnLBAPsiE79vVyK3Cuev.
Pong received: time=114.67 ms
Pong received: time=115.88 ms
Pong received: time=118.80 ms
Pong received: time=103.19 ms
Pong received: time=103.89 ms
Pong received: time=102.34 ms
Pong received: time=110.97 ms
Pong received: time=102.92 ms
Pong received: time=106.53 ms
Pong received: time=114.18 ms
Average latency: 109.34ms

```

closing this issue

**Closed by ElPaisano** 2023-08-21 23:57 UTC
Labels: dif/easy, effort/hours
