### ISSUE TITLE
Explain things in "higher level problems" and easier language

### ISSUE THREAD

**Issue by BMaxV** [ipfs/ipfs-docs#1572] opened 2023-04-23 09:02 UTC
Hi!

I am vaguely familiar with ipfs as in I heard about it years ago and thought it was neat but didn't really have any idea to apply to it. I checked it out again and noticed the docs are written in a very technical way, that probably makes it difficult for regular people to understand what it is and does.

There are also some problems with the structure and the phrasing of the explanations.

Let me quote some examples to explain:

-------------------

The first sentence you see on https://docs.ipfs.tech/ is this:

> The InterPlanetary File System (IPFS) is a set of composable, peer-to-peer protocols for addressing, routing, and transferring content-addressed data in a decentralized file system.

That is technically correct, but it doesn't "mean" anything, and it is unclear what it is implied. If you are using "defined terms"/"jargon" it is generally a good idea to explain them and not assume 100% of the people viewing it are already fully familiar with the terms.

What it is, the problem ipfs solves, file sharing. Specifically your files on your device with other people's devices.

The protocol, different apps and implementations is the way that is done.

The original paper's abstract is way better at explaining this:

>The InterPlanetary File System (IPFS) is a peer-to-peer distributed file system that seeks to connect all computing devices with the same system of files.

Adding "composable, addressing, routing, and transferring content-addressed data" in the *first sentence on the website* is confusing.

--------------

https://docs.ipfs.tech/concepts/ipfs-solves/

>>IPFS and the problems it solves

>Verifiability
>Resilience
>Centralization
>Performance
>Link rot
>Data sovereignty and ownership
>Off-chain storage
>Local-first software
>Vendor lock-in

I personally do not have these problems.

>Verifiability

I do not need to worry about the data that *I already have* being verifiable.

The problem isn't *verifiability*, the problem is *tampering*.

IPFS is built to solve the tampering  tampering problem and verifiability is the *method*.

>IPFS uses cryptographic hashes to verify the authenticity and integrity of files, making it difficult for malicious actors to tamper with or delete files.

Ok, but again, I do not have this problem. I live in a happy friendly bubble where everyone is nice and nobody would tamper with data or delete files, surely? This could be improved with examples.

Is the news article you are reading the news article as it was published or where there changes?

Is this government report the same as before?

This contract document that you are digitally signing, after "fully reading" it?

--------

>Centralization

The problem is indeed centralization. This is correct, (but inconsistent with the way "Verifiability" was written). 

But why is centralization bad?

>IPFS is an open, distributed and participatory network that reduces data silos from centralized servers, making IPFS more resilient than traditional systems. 

That's not it, that's the solution.

>No single entity or person controls,...

> manages or owns IPFS; rather, it is a community-maintained project with multiple implementations of the protocol, multiple tools and apps leveraging that protocol, and multiple users and organizations contributing to it's design and development.

It was getting close there, but it that's also not the problem. The problem isn't even centralized information in itself.

The problem is the power over that information that single people hold by necessity of that design and the single point of failure that can stop a possibly important system from functioning.

This problem is then addressed by the solutions described in that paragraph.

-----------

Finally, it's important to explain things in familiar concepts and terms.

 * IPFS is not a "cloud" owned by a corporation.
 * I understand "private files" on "my cloud". What is the equivalent in IPFS? 
 * Are the files I... "add" private? Can anyone see them?
 * I heard about torrents being evil and people being sued. If I use IPFS, am I breaking the law?

**Comment by johnnymatthews** [comment] 2023-05-16 14:20
Hey @BMaxV, thanks for your input here. You've clearly thought _a lot_ about the problems within the docs. And you're correct; the docs are written in a technically-heavy way -- and that's not ideal.

The reason for this is a combination of audience and resources. The current audience for IPFS is mostly infrastructure engineers who are generally pretty technically minded. On top of that, the IPFS team just doesn't have the resources to rewrite the docs in a beginner-friendly way. There are sections that are geared towards developers that are new to the IPFS ecosystem, like the [Website on IPFS section](https://docs.ipfs.tech/how-to/websites-on-ipfs/single-page-website/).

Due to the limited resources we have on this team, I'm going to close this issue for now. Keep in mind that there are lots of good resources out on the web discussing and explaining IPFS. [Cloudflare has a great introduction](https://developers.cloudflare.com/web3/ipfs-gateway/concepts/ipfs/).

Feel free to add further comments to this thread. Just because the issue is closed doesn't mean we won't read your replies.

**Closed by johnnymatthews** 2023-05-16 14:20 UTC
Labels: need/triage

**Comment by BMaxV** [comment] 2023-05-16 15:32
I really appreciate the reply and I understand completely.

Maybe it's something that's helpful in the future. I'm assuming ipfs is here to stay for a while.
