### ISSUE TITLE
Command-line

### ISSUE THREAD

**Issue by tippi-fifestarr** [ipfs/ipfs-docs#942] opened 2021-11-19 16:51 UTC
When you are using Windows 11 and trying to follow along with the Window's installation instructions, you get stuck at step 5.  This step would benefit by breaking it down into sub-steps, since part 1 is "Add-Content" and then you need to paste or type "C:\users\my_username\documents\windowspowershellp\profile.ps" followed by a bit of mystical code and then finally you can paste the directory you copied in step 4.
![image](https://user-images.githubusercontent.com/62179036/142659627-b593e4cf-fe09-48e7-ac27-27c072985121.png)

![image](https://user-images.githubusercontent.com/62179036/142658494-9a993cfb-ee9f-42a7-bcdf-eb9d8f20b103.png)

based on my limited experience and frustration yesterday, I'm guessing that things are different from Windows 10 to 11?

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2

Still currently working on solving this problem for my system, which was proposed (by elpranocotro#4529 on discord) as a solution or way of verifying something about a bug in my Brave browser where I couldn't load an IPFS .json.  

It seems worthwhile to overcome my lack of knowledge and ability with PowerShell and PATH, however, it is causing a long pause in the debugging process for the other problem.

**Comment by johnnymatthews** [comment] 2021-11-19 17:32
There _shouldn't_ be any difference in Powershell usage between Windows 10 and Windows 11, but I might be wrong. The inner workings of Microsoft are a mystery.

Regardless, I think this might be a duplicate of #940. I'm guessing the problem comes from not having a `profile.ps1` file. I'm booting up my Windows machine now to take a look.

**Comment by johnnymatthews** [comment] 2021-12-03 18:34
I'm gonna close this issue in favor of #940.

**Closed by johnnymatthews** 2021-12-03 18:34 UTC
Labels: need/triage
