### ISSUE TITLE
PRC API response garbled code

### ISSUE THREAD

**Issue by chengpengjava** [ipfs/ipfs-docs#1211] opened 2022-07-22 03:16 UTC
Hello Team,I created IPFS node locally,and then I want to look webui on the browser so I referenced the website:
![image](https://user-images.githubusercontent.com/33616855/180354151-205371e2-4569-4afd-8e20-8f571592f713.png)
I clicked the first raw and then jumped this website:
![image](https://user-images.githubusercontent.com/33616855/180354324-f05c04ab-bcef-41f0-a206-e77b7461027a.png)
so I requested the same PRC API by nodejs:
![image](https://user-images.githubusercontent.com/33616855/180354450-a6e11523-512c-4466-b5f5-aa3b6a377394.png)
![image](https://user-images.githubusercontent.com/33616855/180354860-d7ce97b5-37be-419a-9b5d-1b2e22da0974.png)
and then responsed garbled code,I thought the response data were right because I can see "README.txt" in the garbled code,but I don't konw what's wrong with it.Is my character wrong?Or request headers' content-type wrong?
Thanks

**Comment by johnnymatthews** [comment] 2022-07-25 17:28
I think what's happening here is that you're grabbing the whole DAG instead of just the particular file you want. Try tacking `?filename=README.txt` onto the end of your curl request.

**Comment by johnnymatthews** [comment] 2022-07-25 17:32
Never mind. Looks like this is a duplicate of https://github.com/ipfs/ipfs-docs/issues/1215. Closing this one.

**Closed by johnnymatthews** 2022-07-25 17:32 UTC
Labels: need/triage
