### ISSUE TITLE
Documentation for the REST ls call should enumerate what "Type" integers are or point to more information.

### ISSUE THREAD

**Issue by Erotemic** [ipfs/ipfs-docs#1736] opened 2023-10-17 17:23 UTC
I was playing with ipfsfsspec and noticed that they failed to `ls` one of my directories. The error was because they didn't handle ls return entries with "Type 4". I had no idea what Type 4 was. 

I find the API docs for ls here: http://docs.ipfs.tech.ipns.localhost:8080/reference/kubo/rpc/#api-v0-ls 

And it tells me that Type is an int32 return value, but makes no mention of what the return values mean, nor does it point to information where I can find out. 

I did find some info here: https://ipfs-search.readthedocs.io/en/latest/ipfs_datatypes.html

and here: https://github.com/ipfs/go-unixfs/blob/master/pb/unixfs.proto

and was able to infer type 4 was symlink, but the docs should be updated to make this easier for the next person who wants to figure out how ls works via the REST API. 
```[tasklist]
### Tasks
```

**Comment by lidel** [comment] 2023-10-30 21:54
Thank you for reporting.
This seems to be a duplicate of https://github.com/ipfs/ipfs-docs/issues/1260, let's continue there.

**Closed by lidel** 2023-10-30 21:54 UTC
Labels: need/triage, kind/suggestion
